"""add_user_id

Revision ID: 0f9388d680ba
Revises: b9f569c83c73
Create Date: 2026-06-12 14:18:37.641423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9388d680ba'
down_revision: Union[str, Sequence[str], None] = 'b9f569c83c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可空列
    op.add_column('tasks', sa.Column('owner_id', sa.Integer(), nullable=True))
    # 更新现有数据，设置默认值
    op.execute("UPDATE tasks SET owner_id = 1 WHERE owner_id IS NULL")
    # 改为 NOT NULL
    op.alter_column('tasks', 'owner_id', nullable=False)
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks',
                    ['owner_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.drop_column('tasks', 'owner_id')
    # ### end Alembic commands ###
