"""add task timestamps and indexes

Revision ID: 68f764dde4aa
Revises: 0f9388d680ba
Create Date: 2026-06-16 17:41:43.207879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f764dde4aa'
down_revision: Union[str, Sequence[str], None] = '0f9388d680ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(
        timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_tasks_owner_completed_created_at', 'tasks', [
                    'owner_id', 'completed', 'created_at'], unique=False)
    op.create_index('ix_tasks_owner_created_at', 'tasks', [
                    'owner_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_owner_created_at', table_name='tasks')
    op.drop_index('ix_tasks_owner_completed_created_at', table_name='tasks')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
